services:
  db:
    image: postgres
    container_name: test_postgres2
    networks:
      - dbnetwork
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD= password
      - POSTGRES_DB= testdb2
    volumes:
      - /Users/vincent/test_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    # ports:
    #     - "5432:5432" 

  webserver:
    build: .
    networks:
      - dbnetwork
      - bridge2
    depends_on:
      db:
        condition: service_healthy
    ports:
        - "3000:3000"
    
  
networks:
  dbnetwork:
    name: dbnetwork
    ipam:
      config:
        - subnet: 192.168.1.0/24
    internal: true
  bridge2:
    name: bridge2